import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {scenario,compare} from './scenario.mjs';
const A=await import('./package/dist/animate/research-baseline.mjs');
const R=await import('./package/dist/animate/research-guarded.mjs');
const F=await import('./package/dist/animate/research-forward.mjs');
const cfg={n:2,stagger:99,spring:{mass:1,stiffness:400,damping:800},times:[0,100]};
const a=await scenario(A,cfg,{track:true}),r=await scenario(R,cfg,{track:true}),f=await scenario(F,cfg,{track:true});
const reverse=compare(a,r),forward=compare(a,f);
assert(reverse.maxPosition>1,'reverse positive control must be visibly wrong');
assert(forward.maxPosition<1e-9 && forward.topology===0,'forward preserves this witness');
const ctx={Qt:{p:0,H:0,T:0,J:0}};
const anchor={...A.SurfaceBatch.prototype.Ut.call(ctx,cfg.spring,.1)};
const dir=new URL('./package/dist/animate/',import.meta.url);
const src=await readFile(new URL('research-forward.mjs',dir),'utf8');
const mutated=src.replace('s.steps[j+3]=-q.T;','s.steps[j+3]=q.T;');
assert.notEqual(mutated,src);
await writeFile(new URL('research-mutant.mjs',dir),mutated);
const M=await import(new URL('research-mutant.mjs',dir));
const ordinary={n:100,stagger:1,spring:{mass:1,stiffness:170,damping:26},times:Array.from({length:60},(_,i)=>i*1000/120)};
const base=await scenario(A,ordinary,{track:true}),mutant=await scenario(M,ordinary,{track:true});
const sabotage=compare(base,mutant);assert(sabotage.maxPosition>1,'sign mutant must fail numerical oracle');
// Simplification: one exact step slot instead of two. Arithmetic is identical;
// only the amount of re-computation is examined here, not a timed speed claim.
const single=src.replace('new Float64Array(10)','new Float64Array(5)').replace('(s.next+1)%2','(s.next+1)%1').replace('Math.min(2,s.count+1)','Math.min(1,s.count+1)');
await writeFile(new URL('research-single-slot.mjs',dir),single);
const S=await import(new URL('research-single-slot.mjs',dir));
const simple=await scenario(S,ordinary,{track:true});const two=await scenario(F,ordinary,{track:true});
assert(compare(base,simple).maxPosition<1e-9);
const result={cfg,reverse,forward,anchor,baselineWitness:a.states.at(-1)[2],reverseWitness:r.states.at(-1)[2],forwardWitness:f.states.at(-1)[2],sabotage,simplification:{oneSlot:simple.phase,twoSlots:two.phase}};
await writeFile(new URL('controls.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
