allowBuilds:
  esbuild: true
minimumReleaseAge: 1440
overrides:
  seroval@<1.6.3: ^1.6.3
  brace-expansion@<=5.0.11: ^5.0.12
  browserslist: ^4.28.7
  esbuild: ^0.28.1
  fast-uri: ^3.1.8
  postcss@<=8.5.17: ^8.5.18
  qs: ^6.16.0
  nanoid@<3.3.18: ^3.3.18
  shell-quote@<1.11.0: ^1.11.0
pmOnFail: error
peerDependencyRules:
  allowedVersions:
    "@builder.io/qwik>vite": "8"
patchedDependencies:
  vitepress@2.0.0-alpha.20: patches/vitepress@2.0.0-alpha.20.patch
  "@stryker-mutator/vitest-runner@10.0.0": patches/@stryker-mutator__vitest-runner@10.0.0.patch
