import { chromium } from '@playwright/test';

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1100, height: 850 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:4178/', { waitUntil: 'networkidle' });
  const state = page.locator('#sheet-state');
  if (await state.textContent() !== 'Панель закрыта') throw new Error('Исходная панель не закрыта');
  await page.locator('#open-sheet').click();
  if (await state.textContent() !== 'Панель раскрыта') throw new Error('Панель не раскрылась');
  await page.locator('#note').fill('Увидеть старую оранжерею');
  await page.locator('#note-form button').click();
  await page.locator('[data-select-place="next"]').click();
  if (await page.locator('#place-title').textContent() !== 'Музей графики') throw new Error('Смена точки не обновила детали');
  await page.locator('[data-select-place="previous"]').click();
  if (await page.locator('#note').inputValue() !== 'Увидеть старую оранжерею') throw new Error('Заметка потеряна при возврате');
  await page.locator('#handle').focus();
  await page.keyboard.press('End');
  if (await state.textContent() !== 'Панель закрыта') throw new Error('Клавиатура не закрыла панель');
  await page.keyboard.press('ArrowUp');
  if (await state.textContent() !== 'Панель наполовину') throw new Error('Клавиатура не открыла среднее положение');
  await page.locator('#quiet-sheet').click();
  await page.locator('[data-snap="0"]').click();
  if (await page.locator('#quiet').getAttribute('aria-pressed') !== 'true') throw new Error('Режим без движения не включился');
  if (await state.textContent() !== 'Панель раскрыта') throw new Error('Snap не сработал в режиме без движения');
  await page.screenshot({ path: 'examples/itinerary-sheet/.artifacts/desktop.png' });
  await page.locator('#quiet-sheet').click();
  await page.setViewportSize({ width: 430, height: 650 });
  await page.locator('[data-snap="2"]').click();
  await page.waitForTimeout(500);
  const handle = await page.locator('#handle').boundingBox();
  if (!handle) throw new Error('Ручка не видна');
  const x = handle.x + handle.width / 3, y = handle.y + handle.height / 2;
  await page.mouse.move(x, y); await page.mouse.down();
  await page.setViewportSize({ width: 460, height: 710 });
  await page.mouse.move(x, y - 220, { steps: 8 }); await page.mouse.up();
  if (await state.textContent() === 'Панель закрыта') throw new Error('Pointer-жест не выбрал открытое положение');
  await page.locator('[data-snap="2"]').click();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.locator('[data-snap="0"]').click();
  if (await state.textContent() !== 'Панель раскрыта') throw new Error('Reduced-motion не сохранил доступную цель');
  await page.locator('[data-snap="2"]').click();
  await page.evaluate(() => { dispatchEvent(new PageTransitionEvent('pagehide', { persisted: true })); dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })); });
  await page.locator('#open-sheet').click();
  if (await state.textContent() !== 'Панель раскрыта') throw new Error('Контроллер не восстановился при возврате');
  await page.waitForTimeout(700);
  await page.screenshot({ path: 'examples/itinerary-sheet/.artifacts/mobile.png' });
  if (errors.length) throw new Error(`Ошибки страницы: ${errors.join('; ')}`);
  process.stdout.write('Itinerary sheet smoke: PASS\n');
} finally { await browser.close(); }
