import { chromium } from '@playwright/test';

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1220, height: 900 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:4179/', { waitUntil: 'networkidle' });
  const rows = page.locator('[data-id]');
  if (await rows.count() !== 4) throw new Error('Исходные сцены не показаны');
  if (await page.locator('[data-id="portrait"] [data-time]').textContent() !== '09:15') throw new Error('Исходное расписание неверно');
  await page.locator('[data-id="quay"] [data-move="previous"]').click();
  if (await rows.nth(1).getAttribute('data-id') !== 'quay') throw new Error('Одиночный шаг не изменил порядок');
  if (await page.locator('[data-id="quay"] [data-time]').textContent() !== '09:15') throw new Error('Порядок не изменил расчёт времени');
  await page.locator('#filter').selectOption('ready');
  if (await rows.count() !== 3) throw new Error('Фильтр не скрыл снятую сцену');
  await page.locator('[data-id="portrait"] [data-grip]').focus();
  await page.keyboard.press('Enter'); await page.keyboard.press('Home');
  if (await rows.first().getAttribute('data-id') !== 'portrait') throw new Error('Клавиатура не переместила сцену');
  await page.keyboard.press('Escape');
  if (await rows.first().getAttribute('data-id') !== 'window') throw new Error('Escape не вернул порядок');
  if (await page.evaluate(() => document.activeElement?.closest('[data-id]')?.getAttribute('data-id')) !== 'portrait') throw new Error('Escape потерял фокус');
  const title = page.locator('[data-id="portrait"] [data-title]');
  await title.fill('Портрет — вечерний свет');
  await page.locator('[data-id="portrait"] [data-minutes]').fill('65');
  await page.locator('[data-id="portrait"] [data-minutes]').blur();
  if (await page.locator('#finish-label').textContent() !== 'Окончание 11:45') throw new Error('Длительность не пересчитала конец дня');
  await page.waitForTimeout(600);
  const grip = await page.locator('[data-id="window"] [data-grip]').boundingBox();
  const target = await page.locator('[data-id="portrait"]').boundingBox();
  if (!grip || !target) throw new Error('Строки не измерены');
  await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2); await page.mouse.down();
  await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2, { steps: 6 }); await page.mouse.up();
  if (await rows.first().getAttribute('data-id') === 'window') throw new Error('Pointer не переместил строку');
  if (await title.inputValue() !== 'Портрет — вечерний свет') throw new Error('Правка названия потеряна после перестановки');
  await page.waitForTimeout(450);
  await page.screenshot({ path: 'examples/call-sheet/.artifacts/desktop.png', fullPage: true });
  await page.locator('#direction').click();
  if (await page.locator('#schedule').getAttribute('dir') !== 'rtl') throw new Error('RTL не применён');
  await page.locator('#quiet').click();
  if (await page.locator('#quiet').getAttribute('aria-pressed') !== 'true') throw new Error('Без движения не включено');
  await page.locator('#filter').selectOption('done');
  await page.locator('[data-id="detail"] [data-remove]').click();
  if (!await page.locator('#empty').isVisible()) throw new Error('Пустое представление не показано');
  await page.locator('#new-scene').fill('Закат у окна');
  await page.locator('#new-minutes').fill('30');
  await page.locator('#add-form button').click();
  if (await page.locator('#filter').inputValue() !== 'all') throw new Error('Новая сцена скрыта фильтром');
  if (await page.locator('[data-title]').last().inputValue() !== 'Закат у окна') throw new Error('Новая сцена не показана');
  await page.setViewportSize({ width: 390, height: 800 });
  const longTitle = 'Длинное название сцены о разговоре героев на набережной после заката';
  await page.locator('[data-id="portrait"] [data-title]').fill(longTitle);
  const readable = await page.locator('[data-id="portrait"] [data-title]').evaluate(element =>
    element.scrollHeight <= element.clientHeight + 1 && element.getBoundingClientRect().right <= innerWidth);
  if (!readable) throw new Error('Длинное название обрезано в мобильном RTL');
  await page.screenshot({ path: 'examples/call-sheet/.artifacts/mobile.png', fullPage: true });
  await page.evaluate(() => { dispatchEvent(new PageTransitionEvent('pagehide', { persisted: true })); dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })); });
  await page.locator('[data-id="portrait"] [data-move="previous"]').click();
  if (errors.length) throw new Error(`Ошибки страницы: ${errors.join('; ')}`);
  process.stdout.write('Call sheet smoke: PASS\n');
} finally { await browser.close(); }
