import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import assert from'node:assert/strict';
import{runTransformLifecycleSample,validateTransformLifecycleSample}from'./snapshot/source/scripts/bench-transform-support.mjs';
import{SERVER_PROFILE}from'./snapshot/source/bench/profile/server-profile-registration.mjs';
import{validateServerEngineSample}from'./snapshot/source/bench/profile/server-profile-contract.mjs';
const runner=readFileSync(new URL('./snapshot/source/bench/profile/server-profile-runner.mjs',import.meta.url),'utf8');
const exactSource=runner.slice(runner.indexOf('function threadCpuNs('),runner.indexOf('async function browserTimerProbe(')).replace('export async function measureServerEngine','async function measureServerEngine');
const preserveRawNumbers=value=>typeof value==='number'&&!Number.isFinite(value)?{nonfinite:String(value)}:Array.isArray(value)?value.map(preserveRawNumbers):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,preserveRawNumbers(item)])):value;
const initial=[0,0,1,1,0,0,0],keys=['x','y','scaleX','scaleY','rotate','skewX','skewY'];
const render=v=>`translate(${v[0]}px, ${v[1]}px) scaleX(${v[2]}) scaleY(${v[3]}) rotate(${v[4]}deg) skew(${v[5]}deg, ${v[6]}deg)`;
function syntheticSut({cancelFault=false}={}){const active=new WeakMap(),state=new WeakMap(),writes=[];let calls=0,cancelCalls=0;
 const animate=(targets,props,options)=>{calls++;const existing=new Set(targets.map(t=>active.get(t)).filter(Boolean));for(const owner of existing)owner.cancel();let origin,live=true,finish;const finished=new Promise(resolve=>finish=resolve);const from=targets.map(t=>state.get(t)??initial),to=from.map(v=>keys.map((key,index)=>key in props?(Array.isArray(props[key])?props[key][1]:props[key]):v[index]));
 const tick=time=>{if(!live)return;if(origin===undefined)origin=time;const p=(time-origin)/options.duration;targets.forEach((target,index)=>{const values=from[index].map((v,k)=>v+(to[index][k]-v)*p),text=render(values);state.set(target,values);target.style.setProperty('transform',text);});writes.push({call:calls,timestampMs:time,count:targets.length,first:render(state.get(targets[0])),last:render(state.get(targets.at(-1)))});options.requestFrame(tick);};
 const owner={finished,cancel(){cancelCalls++;if(live){live=false;finish();if(cancelFault&&cancelCalls===1)throw undefined;}}};targets.forEach(t=>active.set(t,owner));options.requestFrame(tick);return owner;};return{animate,writes,read:()=>({calls,cancelCalls})};}
function ownerWithSyntheticProcess({invalidAt=0}={}){const acquired=[];let sequence=0;const fakeProcess={threadCpuUsage(){sequence++;const fields={user:50000+sequence*1000,system:1000+sequence*250};if(sequence===invalidAt)fields.user=NaN;acquired.push({sequence:sequence-1,...fields});return fields;},memoryUsage:()=>({rss:0,heapUsed:0})};
 const measure=Function('process','contextSwitches','runTransformLifecycleSample','validateServerEngineSample','SERVER_PROFILE','preserveRawNumbers',`${exactSource};return measureServerEngine`)(fakeProcess,()=>({voluntary_ctxt_switches:0,nonvoluntary_ctxt_switches:0}),runTransformLifecycleSample,validateServerEngineSample,SERVER_PROFILE,preserveRawNumbers);return{measure,acquired};}
const rows=[];
for(const [sceneIndex,name,sutOptions,cpuOptions]of[[1,'fresh-healthy',{},{}],[0,'live-healthy',{},{}],[1,'fresh-cancel-undefined',{cancelFault:true},{}],[1,'fresh-invalid-acquired-counter',{}, {invalidAt:19}]]){
 const scene=SERVER_PROFILE.engineScenes[sceneIndex],sut=syntheticSut(sutOptions),owner=ownerWithSyntheticProcess(cpuOptions);let output=null,failure=null;
 try{output=await owner.measure(sut.animate,scene);}catch(error){failure={name:error.name,message:error.message,errors:Array.from(error.errors??[],e=>({name:e?.name??typeof e,message:String(e?.message??e),errors:Array.from(e?.errors??[],v=>({type:typeof v,message:String(v?.message??v)}))})),raw:preserveRawNumbers(error.raw)};}
 const success=name.endsWith('healthy');assert.equal(!!output,success,name);const reconstructed=[];
 if(output){validateServerEngineSample(output,scene);for(const raw of output.raw){validateTransformLifecycleSample(raw,scene);assert.equal(raw.raw.clockReads.length,16);assert.equal(raw.raw.cpuReads.length,16);const values=raw.raw.cpuReads.map(read=>(BigInt(read.userUs)+BigInt(read.systemUs))*1000n);raw.raw.clockReads.forEach((read,i)=>assert.equal(read.valueNs,String(values[i])));const intervals=Array.from({length:8},(_,i)=>Number(values[2*i+1]-values[2*i]));assert.equal(intervals[0],raw.operationNs);assert.deepEqual(intervals.slice(1,7),raw.frameNs);assert.equal(intervals[7],raw.cancelDrainNs);const expanded=raw.raw.targetTraces.runs.flatMap(run=>Array.from({length:run.count},()=>run.trace));assert.equal(expanded.length,scene.count);expanded.forEach(trace=>{assert.equal(trace.values.length,6);assert.equal(trace.events.filter(event=>event.phase==='frames').length,6);});reconstructed.push({intervals,counters:values.map(String),expandedTargets:expanded.length,traceRuns:raw.raw.targetTraces.runs.length});}}
 if(name==='fresh-cancel-undefined'){assert.equal(failure.raw.failedRepetition.clockReads.length,15);assert.equal(failure.raw.failedRepetition.cpuReads.length,15);assert.equal(failure.raw.failedRepetition.frameNs.length,6);assert.equal(failure.raw.failedRepetition.unfinishedInterval.afterNs,null);assert.equal(failure.raw.failedRepetition.cleanupCompleted,true);assert(failure.errors[0].errors.some(cause=>cause.type==='undefined'));}
 if(name==='fresh-invalid-acquired-counter'){assert.equal(failure.raw.completed.length,1);assert.equal(failure.raw.failedRepetition.cpuReads.length,3);assert.deepEqual(failure.raw.failedRepetition.cpuReads.at(-1).userUs,{nonfinite:'NaN'});assert.equal(failure.raw.failedRepetition.clockReads.length,2);}
 rows.push({name,synthetic:true,actualTimingSamples:0,scene,acquired:preserveRawNumbers(owner.acquired),writes:sut.writes,output,failure,reconstructed,sut:sut.read()});
}
writeFileSync(new URL('./engine-replay-result.json',import.meta.url),JSON.stringify({frozenFunctionSha256:createHash('sha256').update(exactSource).digest('hex'),rows},null,2)+'\n');console.log(JSON.stringify(rows.map(({name,acquired,output,failure,reconstructed,sut})=>({name,acquired:acquired.length,successfulRepetitions:output?.raw.length??0,failedClockPrefix:failure?.raw?.failedRepetition?.clockReads.length,failedCpuPrefix:failure?.raw?.failedRepetition?.cpuReads.length,reconstructed:reconstructed[0],sut}))));
