import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import assert from'node:assert/strict';
import{nextUp,nextDown}from'./snapshot/source/bench/compare/methodology.mjs';
import{SERVER_PROFILE,serverProfileDigest,serverTailPolicy,planServerSampleSize}from'./snapshot/source/bench/profile/server-profile-registration.mjs';
import{serverOrderStatisticBounds,serverFamilyIntervals,serverBrowserClockBounds,serverBrowserSemanticClockErrorMs}from'./snapshot/source/bench/profile/server-profile-contract.mjs';
const ref=JSON.parse(readFileSync(new URL('./numeric-current-reference.json',import.meta.url)));
const decode=b=>Buffer.from(b,'hex').readDoubleBE(),encode=n=>{const b=Buffer.alloc(8);b.writeDoubleBE(n);return b.toString('hex');};
for(const r of ref.nextafter){assert.equal(encode(nextUp(decode(r.inputBits))),r.upBits);assert.equal(encode(nextDown(decode(r.inputBits))),r.downBits);}
const ranks=ref.exactRanks.map(r=>{const got=serverOrderStatisticBounds(Array.from({length:r.n},(_,i)=>i+1),r.p,1/1600);assert.equal(got.lowRank,r.lowRank);assert.equal(got.highRank,r.highRank);return{...r,got};});
const policy=serverTailPolicy();assert.equal(policy.alphaPerTail,1/1600);assert.equal(policy.minimumBlocks,144);
const cost=ref.costClockCases.map(r=>{const got=serverBrowserClockBounds({beginMs:r.beginMs,endMs:r.endMs},r.hostNs),ideal=Number(r.idealNumerator)/Number(r.idealDenominator);assert(got.low<=ideal&&ideal<=got.high);return{...r,got,enclosed:true};});
const relations=ref.semanticRelationCases.map(r=>{const bound=serverBrowserSemanticClockErrorMs(r.hostNs),error=Number(r.errorNumerator)/Number(r.errorDenominator);assert(error<=bound);return{...r,bound,error,enclosed:true};});
const uncertainty=[288,1024].map(runs=>{const got=serverFamilyIntervals(Array.from({length:10},(_,i)=>({id:String(i),left:Array(runs).fill(100),right:Array(runs).fill(100),leftBounds:Array.from({length:runs},()=>({low:96,high:104})),rightBounds:Array.from({length:runs},()=>({low:96,high:104}))})));assert.equal(got[0].blocks,runs/2);assert(got[0].p95.low<=96/104);assert(got[0].p95.high>=104/96);return{runs,blocks:got[0].blocks,unit:got[0].unit,low:got[0].p95.low,high:got[0].p95.high,systematicBoundDidNotShrink:true};});
const protectedExpected={durationMs:128,toPx:300,repetitions:8,browserBatchCalls:32,browserSemanticCalls:1,warmupRuns:4,pilotRuns:8,minRuns:288,maxRuns:1024,seed:0x53525652,familyAlpha:.05,familySize:10,nonInferiorityUpper:1.05,positiveLower:1.5,positiveWorkMultiplier:2,mdeRelative:.05,power:.8,browserOperationTimeoutMs:30000};
for(const[k,v]of Object.entries(protectedExpected))assert.equal(SERVER_PROFILE[k],v,k);
const plans=[0,.001,.01,.05,.2,1].map(logSd=>({logSd,plan:planServerSampleSize(Array.from({length:10},(_,i)=>({id:String(i),left:Array(8).fill(1),right:Array.from({length:8},(_,j)=>Math.exp((Math.floor(j/2)%2?1:-1)*logSd))})))}));
const inputPaths=['bench/compare/methodology.mjs','bench/profile/server-profile-contract.mjs','bench/profile/server-profile-registration.mjs'];
const result={actualRegisteredTimingSamples:0,protocolDigest:serverProfileDigest(SERVER_PROFILE),clockModelDigest:serverProfileDigest(SERVER_PROFILE.clockError),inputs:inputPaths.map(path=>({path,sha256:createHash('sha256').update(readFileSync(new URL('./snapshot/source/'+path,import.meta.url))).digest('hex')})),referenceSha256:createHash('sha256').update(readFileSync(new URL('./numeric-current-reference.json',import.meta.url))).digest('hex'),nextafter:ref.nextafter,ranks,policy,cost,relations,uncertainty,protectedExpected,plans};
writeFileSync(new URL('./numeric-current-result.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({nextafter:ref.nextafter.length,ranks:ranks.map(r=>({n:r.n,p:r.p,lowRank:r.lowRank,highRank:r.highRank})),costClocks:cost.length,semanticRelations:relations.length,policy,uncertainty,plans,clockModelDigest:result.clockModelDigest}));
